string remote
string source_topic
string destination_topic
uint32 queue_size

# Allows limiting message rate by specifying minimum period in seconds between sent messages
# 0 -> no limits, negative -> no messages sent, positive -> time in seconds between sent messages
float32 period
---
